[package]
name = "fsr2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "*"
bitflags = "*"

[build-dependencies]
bindgen = "0.64.0"
cmake = "0.1"